<?php

declare(strict_types=1);

/*
 * VONQHiringAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VONQHiringAPILib\Tests;

class ClientFactory
{
    public static function create(HttpCallBackCatcher $httpCallback): \VONQHiringAPILib\VONQHiringAPIClient
    {
        $client = (new \VONQHiringAPILib\VONQHiringAPIClient(static::getConfigurationFromEnvironment()))
            ->withConfiguration(static::getTestConfiguration($httpCallback));
        return $client;
    }

    public static function getTestConfiguration(HttpCallBackCatcher $httpCallback): array
    {
        return ['httpCallback' => $httpCallback];
    }

    public static function getConfigurationFromEnvironment(): array
    {
        $config = [];
        $timeout = getenv('VONQ_HIRING_API_LIB_TIMEOUT');
        $numberOfRetries = getenv('VONQ_HIRING_API_LIB_NUMBER_OF_RETRIES');
        $maximumRetryWaitTime = getenv('VONQ_HIRING_API_LIB_MAXIMUM_RETRY_WAIT_TIME');
        $environment = getenv('VONQ_HIRING_API_LIB_ENVIRONMENT');
        $xAuthToken = getenv('VONQ_HIRING_API_LIB_X_AUTH_TOKEN');

        if ($timeout !== false && \is_numeric($timeout)) {
            $config['timeout'] = intval($timeout);
        }

        if ($numberOfRetries !== false && \is_numeric($numberOfRetries)) {
            $config['numberOfRetries'] = intval($numberOfRetries);
        }

        if ($maximumRetryWaitTime !== false && \is_numeric($maximumRetryWaitTime)) {
            $config['maximumRetryWaitTime'] = intval($maximumRetryWaitTime);
        }

        if ($environment !== false) {
            $config['environment'] = $environment;
        }

        if ($xAuthToken !== false) {
            $config['xAuthToken'] = $xAuthToken;
        }

        return $config;
    }
}
