<?php

declare(strict_types=1);

/*
 * VONQHiringAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VONQHiringAPILib\Exceptions;

class CampaignValidationErrorException extends \VONQHiringAPILib\Exceptions\ApiException
{
    /**
     * @var array|null
     */
    private $errors;

    /**
     * @var bool|null
     */
    private $hasErrors;

    /**
     * Returns Errors.
     */
    public function getErrors(): ?array
    {
        return $this->errors;
    }

    /**
     * Sets Errors.
     *
     * @maps errors
     */
    public function setErrors(?array $errors): void
    {
        $this->errors = $errors;
    }

    /**
     * Returns Has Errors.
     */
    public function getHasErrors(): ?bool
    {
        return $this->hasErrors;
    }

    /**
     * Sets Has Errors.
     *
     * @maps has_errors
     */
    public function setHasErrors(?bool $hasErrors): void
    {
        $this->hasErrors = $hasErrors;
    }
}
