<?php

declare(strict_types=1);

/*
 * VONQHiringAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VONQHiringAPILib\Exceptions;

class GenericErrorWithDetailException extends \VONQHiringAPILib\Exceptions\ApiException
{
    /**
     * @var string
     */
    private $detail;

    /**
     * @param string $reason
     * @param \VONQHiringAPILib\Http\HttpRequest $request
     * @param \VONQHiringAPILib\Http\HttpResponse $response
     * @param string $detail
     */
    public function __construct(
        string $reason,
        \VONQHiringAPILib\Http\HttpRequest $request,
        \VONQHiringAPILib\Http\HttpResponse $response,
        string $detail
    ) {
        parent::__construct($reason, $request, $response);
        $this->detail = $detail;
    }

    /**
     * Returns Detail.
     */
    public function getDetail(): string
    {
        return $this->detail;
    }

    /**
     * Sets Detail.
     *
     * @required
     * @maps detail
     */
    public function setDetail(string $detail): void
    {
        $this->detail = $detail;
    }
}
