<?php

declare(strict_types=1);

/*
 * VONQHiringAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VONQHiringAPILib\Exceptions;

class OrderCampaignErrorResponseException extends \VONQHiringAPILib\Exceptions\ApiException
{
    /**
     * @var string[]|null
     */
    private $companyId;

    /**
     * @var \VONQHiringAPILib\Models\PostingDetailsValidationError|null
     */
    private $postingDetails;

    /**
     * @var \VONQHiringAPILib\Models\TargetGroupValidationError|null
     */
    private $targetGroup;

    /**
     * @var \VONQHiringAPILib\Models\RecruiterInfoValidationError|null
     */
    private $recruiterInfo;

    /**
     * @var string[]|null
     */
    private $orderedProducts;

    /**
     * @var \VONQHiringAPILib\Models\OrderedProductsSpecValidationError[]|null
     */
    private $orderedProductsSpecs;

    /**
     * @var string[]|null
     */
    private $orderReference;

    /**
     * @var string[]|null
     */
    private $campaignName;

    /**
     * @var string[]|null
     */
    private $walletId;

    /**
     * @var string[]|null
     */
    private $currency;

    /**
     * Returns Company Id.
     *
     * @return string[]|null
     */
    public function getCompanyId(): ?array
    {
        return $this->companyId;
    }

    /**
     * Sets Company Id.
     *
     * @maps companyId
     *
     * @param string[]|null $companyId
     */
    public function setCompanyId(?array $companyId): void
    {
        $this->companyId = $companyId;
    }

    /**
     * Returns Posting Details.
     */
    public function getPostingDetails(): ?\VONQHiringAPILib\Models\PostingDetailsValidationError
    {
        return $this->postingDetails;
    }

    /**
     * Sets Posting Details.
     *
     * @maps postingDetails
     */
    public function setPostingDetails(?\VONQHiringAPILib\Models\PostingDetailsValidationError $postingDetails): void
    {
        $this->postingDetails = $postingDetails;
    }

    /**
     * Returns Target Group.
     */
    public function getTargetGroup(): ?\VONQHiringAPILib\Models\TargetGroupValidationError
    {
        return $this->targetGroup;
    }

    /**
     * Sets Target Group.
     *
     * @maps targetGroup
     */
    public function setTargetGroup(?\VONQHiringAPILib\Models\TargetGroupValidationError $targetGroup): void
    {
        $this->targetGroup = $targetGroup;
    }

    /**
     * Returns Recruiter Info.
     */
    public function getRecruiterInfo(): ?\VONQHiringAPILib\Models\RecruiterInfoValidationError
    {
        return $this->recruiterInfo;
    }

    /**
     * Sets Recruiter Info.
     *
     * @maps recruiterInfo
     */
    public function setRecruiterInfo(?\VONQHiringAPILib\Models\RecruiterInfoValidationError $recruiterInfo): void
    {
        $this->recruiterInfo = $recruiterInfo;
    }

    /**
     * Returns Ordered Products.
     *
     * @return string[]|null
     */
    public function getOrderedProducts(): ?array
    {
        return $this->orderedProducts;
    }

    /**
     * Sets Ordered Products.
     *
     * @maps orderedProducts
     *
     * @param string[]|null $orderedProducts
     */
    public function setOrderedProducts(?array $orderedProducts): void
    {
        $this->orderedProducts = $orderedProducts;
    }

    /**
     * Returns Ordered Products Specs.
     *
     * @return \VONQHiringAPILib\Models\OrderedProductsSpecValidationError[]|null
     */
    public function getOrderedProductsSpecs(): ?array
    {
        return $this->orderedProductsSpecs;
    }

    /**
     * Sets Ordered Products Specs.
     *
     * @maps orderedProductsSpecs
     *
     * @param \VONQHiringAPILib\Models\OrderedProductsSpecValidationError[]|null $orderedProductsSpecs
     */
    public function setOrderedProductsSpecs(?array $orderedProductsSpecs): void
    {
        $this->orderedProductsSpecs = $orderedProductsSpecs;
    }

    /**
     * Returns Order Reference.
     *
     * @return string[]|null
     */
    public function getOrderReference(): ?array
    {
        return $this->orderReference;
    }

    /**
     * Sets Order Reference.
     *
     * @maps orderReference
     *
     * @param string[]|null $orderReference
     */
    public function setOrderReference(?array $orderReference): void
    {
        $this->orderReference = $orderReference;
    }

    /**
     * Returns Campaign Name.
     *
     * @return string[]|null
     */
    public function getCampaignName(): ?array
    {
        return $this->campaignName;
    }

    /**
     * Sets Campaign Name.
     *
     * @maps campaignName
     *
     * @param string[]|null $campaignName
     */
    public function setCampaignName(?array $campaignName): void
    {
        $this->campaignName = $campaignName;
    }

    /**
     * Returns Wallet Id.
     *
     * @return string[]|null
     */
    public function getWalletId(): ?array
    {
        return $this->walletId;
    }

    /**
     * Sets Wallet Id.
     *
     * @maps walletId
     *
     * @param string[]|null $walletId
     */
    public function setWalletId(?array $walletId): void
    {
        $this->walletId = $walletId;
    }

    /**
     * Returns Currency.
     *
     * @return string[]|null
     */
    public function getCurrency(): ?array
    {
        return $this->currency;
    }

    /**
     * Sets Currency.
     *
     * @maps currency
     *
     * @param string[]|null $currency
     */
    public function setCurrency(?array $currency): void
    {
        $this->currency = $currency;
    }
}
