<?php

declare(strict_types=1);

/*
 * VONQHiringAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VONQHiringAPILib\Exceptions;

class TakeCampaignOfflineNotFoundErrorResponseException extends \VONQHiringAPILib\Exceptions\ApiException
{
    /**
     * @var string
     */
    private $campaignId;

    /**
     * @param string $reason
     * @param \VONQHiringAPILib\Http\HttpRequest $request
     * @param \VONQHiringAPILib\Http\HttpResponse $response
     * @param string $campaignId
     */
    public function __construct(
        string $reason,
        \VONQHiringAPILib\Http\HttpRequest $request,
        \VONQHiringAPILib\Http\HttpResponse $response,
        string $campaignId
    ) {
        parent::__construct($reason, $request, $response);
        $this->campaignId = $campaignId;
    }

    /**
     * Returns Campaign Id.
     */
    public function getCampaignId(): string
    {
        return $this->campaignId;
    }

    /**
     * Sets Campaign Id.
     *
     * @required
     * @maps campaignId
     */
    public function setCampaignId(string $campaignId): void
    {
        $this->campaignId = $campaignId;
    }
}
