<?php

declare(strict_types=1);

/*
 * VONQHiringAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VONQHiringAPILib\Exceptions;

class WalletValidationErrorException extends \VONQHiringAPILib\Exceptions\ApiException
{
    /**
     * @var string[]|null
     */
    private $customerName;

    /**
     * Returns Customer Name.
     *
     * @return string[]|null
     */
    public function getCustomerName(): ?array
    {
        return $this->customerName;
    }

    /**
     * Sets Customer Name.
     *
     * @maps customerName
     *
     * @param string[]|null $customerName
     */
    public function setCustomerName(?array $customerName): void
    {
        $this->customerName = $customerName;
    }
}
