<?php

declare(strict_types=1);

/*
 * VONQHiringAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VONQHiringAPILib\Models;

use stdClass;

class CampaignStatus implements \JsonSerializable
{
    /**
     * @var string
     */
    private $campaignId;

    /**
     * @var string
     */
    private $status;

    /**
     * @var OrderedProductsStatusItem[]|null
     */
    private $orderedProductsStatuses;

    /**
     * @param string $campaignId
     * @param string $status
     */
    public function __construct(string $campaignId, string $status)
    {
        $this->campaignId = $campaignId;
        $this->status = $status;
    }

    /**
     * Returns Campaign Id.
     */
    public function getCampaignId(): string
    {
        return $this->campaignId;
    }

    /**
     * Sets Campaign Id.
     *
     * @required
     * @maps campaignId
     */
    public function setCampaignId(string $campaignId): void
    {
        $this->campaignId = $campaignId;
    }

    /**
     * Returns Status.
     * Status of the campaign. One of the following
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * Status of the campaign. One of the following
     *
     * @required
     * @maps status
     * @factory \VONQHiringAPILib\Models\StatusEnum::checkValue
     */
    public function setStatus(string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Ordered Products Statuses.
     *
     * @return OrderedProductsStatusItem[]|null
     */
    public function getOrderedProductsStatuses(): ?array
    {
        return $this->orderedProductsStatuses;
    }

    /**
     * Sets Ordered Products Statuses.
     *
     * @maps orderedProductsStatuses
     *
     * @param OrderedProductsStatusItem[]|null $orderedProductsStatuses
     */
    public function setOrderedProductsStatuses(?array $orderedProductsStatuses): void
    {
        $this->orderedProductsStatuses = $orderedProductsStatuses;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['campaignId']                  = $this->campaignId;
        $json['status']                      = StatusEnum::checkValue($this->status);
        if (isset($this->orderedProductsStatuses)) {
            $json['orderedProductsStatuses'] = $this->orderedProductsStatuses;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
