<?php

declare(strict_types=1);

/*
 * VONQHiringAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VONQHiringAPILib\Models;

use stdClass;

class CampaignPosting implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $name;

    /**
     * @var int|null
     */
    private $clicks;

    /**
     * @var string|null
     */
    private $productId;

    /**
     * Returns Name.
     * The name of the Product that was bought
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * The name of the Product that was bought
     *
     * @maps name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Clicks.
     * Number of clicks of the mentioned posting
     */
    public function getClicks(): ?int
    {
        return $this->clicks;
    }

    /**
     * Sets Clicks.
     * Number of clicks of the mentioned posting
     *
     * @maps clicks
     */
    public function setClicks(?int $clicks): void
    {
        $this->clicks = $clicks;
    }

    /**
     * Returns Product Id.
     * The ID of the product that was bought
     */
    public function getProductId(): ?string
    {
        return $this->productId;
    }

    /**
     * Sets Product Id.
     * The ID of the product that was bought
     *
     * @maps productId
     */
    public function setProductId(?string $productId): void
    {
        $this->productId = $productId;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->name)) {
            $json['name']      = $this->name;
        }
        if (isset($this->clicks)) {
            $json['clicks']    = $this->clicks;
        }
        if (isset($this->productId)) {
            $json['productId'] = $this->productId;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
