<?php

declare(strict_types=1);

/*
 * VONQHiringAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VONQHiringAPILib\Models;

use stdClass;

class Duration implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $range;

    /**
     * @var int|null
     */
    private $period;

    /**
     * Returns Range.
     * The range of the duration
     */
    public function getRange(): ?string
    {
        return $this->range;
    }

    /**
     * Sets Range.
     * The range of the duration
     *
     * @maps range
     * @factory \VONQHiringAPILib\Models\DurationRangeEnum::checkValue
     */
    public function setRange(?string $range): void
    {
        $this->range = $range;
    }

    /**
     * Returns Period.
     * The duration a vacancy is actively listed on a channel
     */
    public function getPeriod(): ?int
    {
        return $this->period;
    }

    /**
     * Sets Period.
     * The duration a vacancy is actively listed on a channel
     *
     * @maps period
     */
    public function setPeriod(?int $period): void
    {
        $this->period = $period;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->range)) {
            $json['range']  = DurationRangeEnum::checkValue($this->range);
        }
        if (isset($this->period)) {
            $json['period'] = $this->period;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
