<?php

declare(strict_types=1);

/*
 * VONQHiringAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VONQHiringAPILib\Models;

use stdClass;

class FacetAutocomplete implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $term;

    /**
     * @var array|null
     */
    private $credentials;

    /**
     * Returns Term.
     */
    public function getTerm(): ?string
    {
        return $this->term;
    }

    /**
     * Sets Term.
     *
     * @maps term
     */
    public function setTerm(?string $term): void
    {
        $this->term = $term;
    }

    /**
     * Returns Credentials.
     * An object with `contract_credentials` data
     */
    public function getCredentials(): ?array
    {
        return $this->credentials;
    }

    /**
     * Sets Credentials.
     * An object with `contract_credentials` data
     *
     * @maps credentials
     */
    public function setCredentials(?array $credentials): void
    {
        $this->credentials = $credentials;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->term)) {
            $json['term']        = $this->term;
        }
        if (isset($this->credentials)) {
            $json['credentials'] = $this->credentials;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
