<?php

declare(strict_types=1);

/*
 * VONQHiringAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VONQHiringAPILib\Models;

use stdClass;

class JobTitle implements \JsonSerializable
{
    /**
     * @var int
     */
    private $id;

    /**
     * @var string
     */
    private $name;

    /**
     * @var LimitedJobFunction
     */
    private $jobFunction;

    /**
     * @param int $id
     * @param string $name
     * @param LimitedJobFunction $jobFunction
     */
    public function __construct(int $id, string $name, LimitedJobFunction $jobFunction)
    {
        $this->id = $id;
        $this->name = $name;
        $this->jobFunction = $jobFunction;
    }

    /**
     * Returns Id.
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * Sets Id.
     *
     * @required
     * @maps id
     */
    public function setId(int $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Name.
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     *
     * @required
     * @maps name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Job Function.
     * JobFunction object that doesn't
     * follow nested relationships
     */
    public function getJobFunction(): LimitedJobFunction
    {
        return $this->jobFunction;
    }

    /**
     * Sets Job Function.
     * JobFunction object that doesn't
     * follow nested relationships
     *
     * @required
     * @maps job_function
     */
    public function setJobFunction(LimitedJobFunction $jobFunction): void
    {
        $this->jobFunction = $jobFunction;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['id']           = $this->id;
        $json['name']         = $this->name;
        $json['job_function'] = $this->jobFunction;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
