<?php

declare(strict_types=1);

/*
 * VONQHiringAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VONQHiringAPILib\Models;

use stdClass;

/**
 * Location object that doesn't
 * follow nested relationships
 */
class LimitedLocation implements \JsonSerializable
{
    /**
     * @var int
     */
    private $id;

    /**
     * @var string
     */
    private $canonicalName;

    /**
     * @param int $id
     * @param string $canonicalName
     */
    public function __construct(int $id, string $canonicalName)
    {
        $this->id = $id;
        $this->canonicalName = $canonicalName;
    }

    /**
     * Returns Id.
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * Sets Id.
     *
     * @required
     * @maps id
     */
    public function setId(int $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Canonical Name.
     */
    public function getCanonicalName(): string
    {
        return $this->canonicalName;
    }

    /**
     * Sets Canonical Name.
     *
     * @required
     * @maps canonical_name
     */
    public function setCanonicalName(string $canonicalName): void
    {
        $this->canonicalName = $canonicalName;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['id']             = $this->id;
        $json['canonical_name'] = $this->canonicalName;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
