<?php

declare(strict_types=1);

/*
 * VONQHiringAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VONQHiringAPILib\Models;

use stdClass;

class OrganizationValidationError implements \JsonSerializable
{
    /**
     * @var string[]|null
     */
    private $name;

    /**
     * @var string[]|null
     */
    private $companyLogo;

    /**
     * Returns Name.
     *
     * @return string[]|null
     */
    public function getName(): ?array
    {
        return $this->name;
    }

    /**
     * Sets Name.
     *
     * @maps name
     *
     * @param string[]|null $name
     */
    public function setName(?array $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Company Logo.
     *
     * @return string[]|null
     */
    public function getCompanyLogo(): ?array
    {
        return $this->companyLogo;
    }

    /**
     * Sets Company Logo.
     *
     * @maps companyLogo
     *
     * @param string[]|null $companyLogo
     */
    public function setCompanyLogo(?array $companyLogo): void
    {
        $this->companyLogo = $companyLogo;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->name)) {
            $json['name']        = $this->name;
        }
        if (isset($this->companyLogo)) {
            $json['companyLogo'] = $this->companyLogo;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
