<?php

declare(strict_types=1);

/*
 * VONQHiringAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VONQHiringAPILib\Models;

use stdClass;

/**
 * A paginated list of campaigns.
 */
class PaginatedCampaignList implements \JsonSerializable
{
    /**
     * @var int
     */
    private $total;

    /**
     * @var int
     */
    private $limit;

    /**
     * @var int
     */
    private $offset;

    /**
     * @var Meta
     */
    private $meta;

    /**
     * @var Campaign[]
     */
    private $data;

    /**
     * @param int $total
     * @param int $limit
     * @param int $offset
     * @param Meta $meta
     * @param Campaign[] $data
     */
    public function __construct(int $total, int $limit, int $offset, Meta $meta, array $data)
    {
        $this->total = $total;
        $this->limit = $limit;
        $this->offset = $offset;
        $this->meta = $meta;
        $this->data = $data;
    }

    /**
     * Returns Total.
     * Total number of results.
     */
    public function getTotal(): int
    {
        return $this->total;
    }

    /**
     * Sets Total.
     * Total number of results.
     *
     * @required
     * @maps total
     */
    public function setTotal(int $total): void
    {
        $this->total = $total;
    }

    /**
     * Returns Limit.
     * Limit the number of results retrieved.
     */
    public function getLimit(): int
    {
        return $this->limit;
    }

    /**
     * Sets Limit.
     * Limit the number of results retrieved.
     *
     * @required
     * @maps limit
     */
    public function setLimit(int $limit): void
    {
        $this->limit = $limit;
    }

    /**
     * Returns Offset.
     * Return results starting from this `offset`
     */
    public function getOffset(): int
    {
        return $this->offset;
    }

    /**
     * Sets Offset.
     * Return results starting from this `offset`
     *
     * @required
     * @maps offset
     */
    public function setOffset(int $offset): void
    {
        $this->offset = $offset;
    }

    /**
     * Returns Meta.
     */
    public function getMeta(): Meta
    {
        return $this->meta;
    }

    /**
     * Sets Meta.
     *
     * @required
     * @maps meta
     */
    public function setMeta(Meta $meta): void
    {
        $this->meta = $meta;
    }

    /**
     * Returns Data.
     *
     * @return Campaign[]
     */
    public function getData(): array
    {
        return $this->data;
    }

    /**
     * Sets Data.
     *
     * @required
     * @maps data
     *
     * @param Campaign[] $data
     */
    public function setData(array $data): void
    {
        $this->data = $data;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['total']  = $this->total;
        $json['limit']  = $this->limit;
        $json['offset'] = $this->offset;
        $json['meta']   = $this->meta;
        $json['data']   = $this->data;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
