<?php

declare(strict_types=1);

/*
 * VONQHiringAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VONQHiringAPILib\Models;

use stdClass;

class PaginatedProductList implements \JsonSerializable
{
    /**
     * @var int
     */
    private $count;

    /**
     * @var array[]
     */
    private $facets;

    /**
     * @var string|null
     */
    private $next;

    /**
     * @var string|null
     */
    private $previous;

    /**
     * @var Product[]
     */
    private $results;

    /**
     * @param int $count
     * @param array[] $facets
     * @param Product[] $results
     */
    public function __construct(int $count, array $facets, array $results)
    {
        $this->count = $count;
        $this->facets = $facets;
        $this->results = $results;
    }

    /**
     * Returns Count.
     * Total number of products.
     */
    public function getCount(): int
    {
        return $this->count;
    }

    /**
     * Sets Count.
     * Total number of products.
     *
     * @required
     * @maps count
     */
    public function setCount(int $count): void
    {
        $this->count = $count;
    }

    /**
     * Returns Facets.
     *
     * @return array[]
     */
    public function getFacets(): array
    {
        return $this->facets;
    }

    /**
     * Sets Facets.
     *
     * @required
     * @maps facets
     *
     * @param array[] $facets
     */
    public function setFacets(array $facets): void
    {
        $this->facets = $facets;
    }

    /**
     * Returns Next.
     * Path to the next page of results, if any.
     */
    public function getNext(): ?string
    {
        return $this->next;
    }

    /**
     * Sets Next.
     * Path to the next page of results, if any.
     *
     * @maps next
     */
    public function setNext(?string $next): void
    {
        $this->next = $next;
    }

    /**
     * Returns Previous.
     * Path to the previous page of results, if any.
     */
    public function getPrevious(): ?string
    {
        return $this->previous;
    }

    /**
     * Sets Previous.
     * Path to the previous page of results, if any.
     *
     * @maps previous
     */
    public function setPrevious(?string $previous): void
    {
        $this->previous = $previous;
    }

    /**
     * Returns Results.
     *
     * @return Product[]
     */
    public function getResults(): array
    {
        return $this->results;
    }

    /**
     * Sets Results.
     *
     * @required
     * @maps results
     *
     * @param Product[] $results
     */
    public function setResults(array $results): void
    {
        $this->results = $results;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['count']    = $this->count;
        $json['facets']   = $this->facets;
        $json['next']     = $this->next;
        $json['previous'] = $this->previous;
        $json['results']  = $this->results;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
