<?php

declare(strict_types=1);

/*
 * VONQHiringAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VONQHiringAPILib\Models;

use stdClass;

/**
 * Optional source for the parameters made of parameter name as key and source for the parameter value
 * as object
 */
class ParametersSource implements \JsonSerializable
{
    /**
     * @var Term|null
     */
    private $term;

    /**
     * Returns Term.
     */
    public function getTerm(): ?Term
    {
        return $this->term;
    }

    /**
     * Sets Term.
     *
     * @maps term
     */
    public function setTerm(?Term $term): void
    {
        $this->term = $term;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->term)) {
            $json['term'] = $this->term;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
