<?php

declare(strict_types=1);

/*
 * VONQHiringAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VONQHiringAPILib\Models;

use stdClass;

/**
 * Most job boards require a salary indication to be provided. This is a required field to be able to
 * offer a standardized check out experience for all 5000+ channels we offer, and to enable fast
 * campaign delivery.
 */
class PostingSalaryIndication implements \JsonSerializable
{
    /**
     * @var string
     */
    private $period;

    /**
     * @var SalaryRange
     */
    private $range;

    /**
     * @param string $period
     * @param SalaryRange $range
     */
    public function __construct(string $period, SalaryRange $range)
    {
        $this->period = $period;
        $this->range = $range;
    }

    /**
     * Returns Period.
     */
    public function getPeriod(): string
    {
        return $this->period;
    }

    /**
     * Sets Period.
     *
     * @required
     * @maps period
     * @factory \VONQHiringAPILib\Models\PeriodEnum::checkValue
     */
    public function setPeriod(string $period): void
    {
        $this->period = $period;
    }

    /**
     * Returns Range.
     */
    public function getRange(): SalaryRange
    {
        return $this->range;
    }

    /**
     * Sets Range.
     *
     * @required
     * @maps range
     */
    public function setRange(SalaryRange $range): void
    {
        $this->range = $range;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['period'] = PeriodEnum::checkValue($this->period);
        $json['range']  = $this->range;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
