<?php

declare(strict_types=1);

/*
 * VONQHiringAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VONQHiringAPILib\Models;

use stdClass;

class Product implements \JsonSerializable
{
    /**
     * @var string
     */
    private $title;

    /**
     * @var LimitedLocation[]
     */
    private $locations;

    /**
     * @var LimitedJobFunction[]
     */
    private $jobFunctions;

    /**
     * @var Industry[]
     */
    private $industries;

    /**
     * @var string|null
     */
    private $description;

    /**
     * @var string|null
     */
    private $homepage;

    /**
     * @var array
     */
    private $logoUrl = [];

    /**
     * @var ProductLogoWithSize[]|null
     */
    private $logoSquareUrl;

    /**
     * @var ProductLogoWithSize[]|null
     */
    private $logoRectangleUrl;

    /**
     * @var DurationInDays
     */
    private $duration;

    /**
     * @var DurationInHours
     */
    private $timeToProcess;

    /**
     * @var DurationInHours
     */
    private $timeToSetup;

    /**
     * @var string
     */
    private $productId;

    /**
     * @var Price[]
     */
    private $vonqPrice;

    /**
     * @var Price[]
     */
    private $ratecardPrice;

    /**
     * @var string
     */
    private $type;

    /**
     * @var string[]
     */
    private $crossPostings;

    /**
     * @var ListChannel
     */
    private $channel;

    /**
     * @var string
     */
    private $audienceGroup;

    /**
     * @var bool
     */
    private $mcEnabled;

    /**
     * @var bool
     */
    private $mcOnly;

    /**
     * @var bool
     */
    private $allowOrders;

    /**
     * @param string $title
     * @param LimitedLocation[] $locations
     * @param LimitedJobFunction[] $jobFunctions
     * @param Industry[] $industries
     * @param DurationInDays $duration
     * @param DurationInHours $timeToProcess
     * @param DurationInHours $timeToSetup
     * @param string $productId
     * @param Price[] $vonqPrice
     * @param Price[] $ratecardPrice
     * @param string $type
     * @param string[] $crossPostings
     * @param ListChannel $channel
     * @param string $audienceGroup
     * @param bool $mcEnabled
     * @param bool $mcOnly
     * @param bool $allowOrders
     */
    public function __construct(
        string $title,
        array $locations,
        array $jobFunctions,
        array $industries,
        DurationInDays $duration,
        DurationInHours $timeToProcess,
        DurationInHours $timeToSetup,
        string $productId,
        array $vonqPrice,
        array $ratecardPrice,
        string $type,
        array $crossPostings,
        ListChannel $channel,
        string $audienceGroup,
        bool $mcEnabled,
        bool $mcOnly,
        bool $allowOrders
    ) {
        $this->title = $title;
        $this->locations = $locations;
        $this->jobFunctions = $jobFunctions;
        $this->industries = $industries;
        $this->duration = $duration;
        $this->timeToProcess = $timeToProcess;
        $this->timeToSetup = $timeToSetup;
        $this->productId = $productId;
        $this->vonqPrice = $vonqPrice;
        $this->ratecardPrice = $ratecardPrice;
        $this->type = $type;
        $this->crossPostings = $crossPostings;
        $this->channel = $channel;
        $this->audienceGroup = $audienceGroup;
        $this->mcEnabled = $mcEnabled;
        $this->mcOnly = $mcOnly;
        $this->allowOrders = $allowOrders;
    }

    /**
     * Returns Title.
     */
    public function getTitle(): string
    {
        return $this->title;
    }

    /**
     * Sets Title.
     *
     * @required
     * @maps title
     */
    public function setTitle(string $title): void
    {
        $this->title = $title;
    }

    /**
     * Returns Locations.
     *
     * @return LimitedLocation[]
     */
    public function getLocations(): array
    {
        return $this->locations;
    }

    /**
     * Sets Locations.
     *
     * @required
     * @maps locations
     *
     * @param LimitedLocation[] $locations
     */
    public function setLocations(array $locations): void
    {
        $this->locations = $locations;
    }

    /**
     * Returns Job Functions.
     *
     * @return LimitedJobFunction[]
     */
    public function getJobFunctions(): array
    {
        return $this->jobFunctions;
    }

    /**
     * Sets Job Functions.
     *
     * @required
     * @maps job_functions
     *
     * @param LimitedJobFunction[] $jobFunctions
     */
    public function setJobFunctions(array $jobFunctions): void
    {
        $this->jobFunctions = $jobFunctions;
    }

    /**
     * Returns Industries.
     *
     * @return Industry[]
     */
    public function getIndustries(): array
    {
        return $this->industries;
    }

    /**
     * Sets Industries.
     *
     * @required
     * @maps industries
     *
     * @param Industry[] $industries
     */
    public function setIndustries(array $industries): void
    {
        $this->industries = $industries;
    }

    /**
     * Returns Description.
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     *
     * @maps description
     */
    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Homepage.
     */
    public function getHomepage(): ?string
    {
        return $this->homepage;
    }

    /**
     * Sets Homepage.
     *
     * @maps homepage
     */
    public function setHomepage(?string $homepage): void
    {
        $this->homepage = $homepage;
    }

    /**
     * Returns Logo Url.
     *
     * @return ProductLogo[]|null
     */
    public function getLogoUrl(): ?array
    {
        if (count($this->logoUrl) == 0) {
            return null;
        }
        return $this->logoUrl['value'];
    }

    /**
     * Sets Logo Url.
     *
     * @maps logo_url
     *
     * @param ProductLogo[]|null $logoUrl
     */
    public function setLogoUrl(?array $logoUrl): void
    {
        $this->logoUrl['value'] = $logoUrl;
    }

    /**
     * Unsets Logo Url.
     */
    public function unsetLogoUrl(): void
    {
        $this->logoUrl = [];
    }

    /**
     * Returns Logo Square Url.
     *
     * @return ProductLogoWithSize[]|null
     */
    public function getLogoSquareUrl(): ?array
    {
        return $this->logoSquareUrl;
    }

    /**
     * Sets Logo Square Url.
     *
     * @maps logo_square_url
     *
     * @param ProductLogoWithSize[]|null $logoSquareUrl
     */
    public function setLogoSquareUrl(?array $logoSquareUrl): void
    {
        $this->logoSquareUrl = $logoSquareUrl;
    }

    /**
     * Returns Logo Rectangle Url.
     *
     * @return ProductLogoWithSize[]|null
     */
    public function getLogoRectangleUrl(): ?array
    {
        return $this->logoRectangleUrl;
    }

    /**
     * Sets Logo Rectangle Url.
     *
     * @maps logo_rectangle_url
     *
     * @param ProductLogoWithSize[]|null $logoRectangleUrl
     */
    public function setLogoRectangleUrl(?array $logoRectangleUrl): void
    {
        $this->logoRectangleUrl = $logoRectangleUrl;
    }

    /**
     * Returns Duration.
     */
    public function getDuration(): DurationInDays
    {
        return $this->duration;
    }

    /**
     * Sets Duration.
     *
     * @required
     * @maps duration
     */
    public function setDuration(DurationInDays $duration): void
    {
        $this->duration = $duration;
    }

    /**
     * Returns Time to Process.
     */
    public function getTimeToProcess(): DurationInHours
    {
        return $this->timeToProcess;
    }

    /**
     * Sets Time to Process.
     *
     * @required
     * @maps time_to_process
     */
    public function setTimeToProcess(DurationInHours $timeToProcess): void
    {
        $this->timeToProcess = $timeToProcess;
    }

    /**
     * Returns Time to Setup.
     */
    public function getTimeToSetup(): DurationInHours
    {
        return $this->timeToSetup;
    }

    /**
     * Sets Time to Setup.
     *
     * @required
     * @maps time_to_setup
     */
    public function setTimeToSetup(DurationInHours $timeToSetup): void
    {
        $this->timeToSetup = $timeToSetup;
    }

    /**
     * Returns Product Id.
     */
    public function getProductId(): string
    {
        return $this->productId;
    }

    /**
     * Sets Product Id.
     *
     * @required
     * @maps product_id
     */
    public function setProductId(string $productId): void
    {
        $this->productId = $productId;
    }

    /**
     * Returns Vonq Price.
     * the price to be displayed to customers
     *
     * @return Price[]
     */
    public function getVonqPrice(): array
    {
        return $this->vonqPrice;
    }

    /**
     * Sets Vonq Price.
     * the price to be displayed to customers
     *
     * @required
     * @maps vonq_price
     *
     * @param Price[] $vonqPrice
     */
    public function setVonqPrice(array $vonqPrice): void
    {
        $this->vonqPrice = $vonqPrice;
    }

    /**
     * Returns Ratecard Price.
     *
     * @return Price[]
     */
    public function getRatecardPrice(): array
    {
        return $this->ratecardPrice;
    }

    /**
     * Sets Ratecard Price.
     *
     * @required
     * @maps ratecard_price
     *
     * @param Price[] $ratecardPrice
     */
    public function setRatecardPrice(array $ratecardPrice): void
    {
        $this->ratecardPrice = $ratecardPrice;
    }

    /**
     * Returns Type.
     * The type of a channel
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * The type of a channel
     *
     * @required
     * @maps type
     * @factory \VONQHiringAPILib\Models\ChannelTypeEnum::checkValue
     */
    public function setType(string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Cross Postings.
     *
     * @return string[]
     */
    public function getCrossPostings(): array
    {
        return $this->crossPostings;
    }

    /**
     * Sets Cross Postings.
     *
     * @required
     * @maps cross_postings
     *
     * @param string[] $crossPostings
     */
    public function setCrossPostings(array $crossPostings): void
    {
        $this->crossPostings = $crossPostings;
    }

    /**
     * Returns Channel.
     */
    public function getChannel(): ListChannel
    {
        return $this->channel;
    }

    /**
     * Sets Channel.
     *
     * @required
     * @maps channel
     */
    public function setChannel(ListChannel $channel): void
    {
        $this->channel = $channel;
    }

    /**
     * Returns Audience Group.
     * The product's audience group (niche/generic)
     */
    public function getAudienceGroup(): string
    {
        return $this->audienceGroup;
    }

    /**
     * Sets Audience Group.
     * The product's audience group (niche/generic)
     *
     * @required
     * @maps audience_group
     * @factory \VONQHiringAPILib\Models\AudienceGroupEnum::checkValue
     */
    public function setAudienceGroup(string $audienceGroup): void
    {
        $this->audienceGroup = $audienceGroup;
    }

    /**
     * Returns Mc Enabled.
     * is My Contract enabled for the channel
     */
    public function getMcEnabled(): bool
    {
        return $this->mcEnabled;
    }

    /**
     * Sets Mc Enabled.
     * is My Contract enabled for the channel
     *
     * @required
     * @maps mc_enabled
     */
    public function setMcEnabled(bool $mcEnabled): void
    {
        $this->mcEnabled = $mcEnabled;
    }

    /**
     * Returns Mc Only.
     * is the product available only for My Contract order
     */
    public function getMcOnly(): bool
    {
        return $this->mcOnly;
    }

    /**
     * Sets Mc Only.
     * is the product available only for My Contract order
     *
     * @required
     * @maps mc_only
     */
    public function setMcOnly(bool $mcOnly): void
    {
        $this->mcOnly = $mcOnly;
    }

    /**
     * Returns Allow Orders.
     * is the product available for order. a campaign cannot be ordered with a product having
     * `allow_orders` set to `false`.
     */
    public function getAllowOrders(): bool
    {
        return $this->allowOrders;
    }

    /**
     * Sets Allow Orders.
     * is the product available for order. a campaign cannot be ordered with a product having
     * `allow_orders` set to `false`.
     *
     * @required
     * @maps allow_orders
     */
    public function setAllowOrders(bool $allowOrders): void
    {
        $this->allowOrders = $allowOrders;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['title']              = $this->title;
        $json['locations']          = $this->locations;
        $json['job_functions']      = $this->jobFunctions;
        $json['industries']         = $this->industries;
        $json['description']        = $this->description;
        $json['homepage']           = $this->homepage;
        if (!empty($this->logoUrl)) {
            $json['logo_url']       = $this->logoUrl['value'];
        }
        $json['logo_square_url']    = $this->logoSquareUrl;
        $json['logo_rectangle_url'] = $this->logoRectangleUrl;
        $json['duration']           = $this->duration;
        $json['time_to_process']    = $this->timeToProcess;
        $json['time_to_setup']      = $this->timeToSetup;
        $json['product_id']         = $this->productId;
        $json['vonq_price']         = $this->vonqPrice;
        $json['ratecard_price']     = $this->ratecardPrice;
        $json['type']               = ChannelTypeEnum::checkValue($this->type);
        $json['cross_postings']     = $this->crossPostings;
        $json['channel']            = $this->channel;
        $json['audience_group']     = AudienceGroupEnum::checkValue($this->audienceGroup);
        $json['mc_enabled']         = $this->mcEnabled;
        $json['mc_only']            = $this->mcOnly;
        $json['allow_orders']       = $this->allowOrders;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
