<?php

declare(strict_types=1);

/*
 * VONQHiringAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VONQHiringAPILib\Models;

use stdClass;

class ProductValidationErrors implements \JsonSerializable
{
    /**
     * @var array
     */
    private $credentials;

    /**
     * @var array
     */
    private $postingRequirements;

    /**
     * @param array $credentials
     * @param array $postingRequirements
     */
    public function __construct(array $credentials, array $postingRequirements)
    {
        $this->credentials = $credentials;
        $this->postingRequirements = $postingRequirements;
    }

    /**
     * Returns Credentials.
     */
    public function getCredentials(): array
    {
        return $this->credentials;
    }

    /**
     * Sets Credentials.
     *
     * @required
     * @maps credentials
     */
    public function setCredentials(array $credentials): void
    {
        $this->credentials = $credentials;
    }

    /**
     * Returns Posting Requirements.
     */
    public function getPostingRequirements(): array
    {
        return $this->postingRequirements;
    }

    /**
     * Sets Posting Requirements.
     *
     * @required
     * @maps posting_requirements
     */
    public function setPostingRequirements(array $postingRequirements): void
    {
        $this->postingRequirements = $postingRequirements;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['credentials']          = $this->credentials;
        $json['posting_requirements'] = $this->postingRequirements;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
