<?php

declare(strict_types=1);

/*
 * VONQHiringAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VONQHiringAPILib\Models;

use stdClass;

/**
 * Logo Object used by the channels or products. Most Products and Channels will have a logo associated.
 * These can be displayed by the partner as square or rectangular.
 */
class ProductLogoWithSize implements \JsonSerializable
{
    /**
     * @var string
     */
    private $url;

    /**
     * @var string
     */
    private $size;

    /**
     * @param string $url
     * @param string $size
     */
    public function __construct(string $url, string $size)
    {
        $this->url = $url;
        $this->size = $size;
    }

    /**
     * Returns Url.
     */
    public function getUrl(): string
    {
        return $this->url;
    }

    /**
     * Sets Url.
     *
     * @required
     * @maps url
     */
    public function setUrl(string $url): void
    {
        $this->url = $url;
    }

    /**
     * Returns Size.
     * Size format: WIDTHxHEIGHT
     */
    public function getSize(): string
    {
        return $this->size;
    }

    /**
     * Sets Size.
     * Size format: WIDTHxHEIGHT
     *
     * @required
     * @maps size
     */
    public function setSize(string $size): void
    {
        $this->size = $size;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['url']  = $this->url;
        $json['size'] = $this->size;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
