<?php

declare(strict_types=1);

/*
 * VONQHiringAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VONQHiringAPILib\Models;

use stdClass;

class PurchasePriceValidationError implements \JsonSerializable
{
    /**
     * @var string[]|null
     */
    private $amount;

    /**
     * @var string[]|null
     */
    private $currency;

    /**
     * Returns Amount.
     *
     * @return string[]|null
     */
    public function getAmount(): ?array
    {
        return $this->amount;
    }

    /**
     * Sets Amount.
     *
     * @maps amount
     *
     * @param string[]|null $amount
     */
    public function setAmount(?array $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * Returns Currency.
     *
     * @return string[]|null
     */
    public function getCurrency(): ?array
    {
        return $this->currency;
    }

    /**
     * Sets Currency.
     *
     * @maps currency
     *
     * @param string[]|null $currency
     */
    public function setCurrency(?array $currency): void
    {
        $this->currency = $currency;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->amount)) {
            $json['amount']   = $this->amount;
        }
        if (isset($this->currency)) {
            $json['currency'] = $this->currency;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
