<?php

declare(strict_types=1);

/*
 * VONQHiringAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VONQHiringAPILib\Models;

use stdClass;

class SalaryRangeValidationError implements \JsonSerializable
{
    /**
     * @var string[]|null
     */
    private $to;

    /**
     * @var string[]|null
     */
    private $from;

    /**
     * @var string[]|null
     */
    private $currency;

    /**
     * Returns To.
     *
     * @return string[]|null
     */
    public function getTo(): ?array
    {
        return $this->to;
    }

    /**
     * Sets To.
     *
     * @maps to
     *
     * @param string[]|null $to
     */
    public function setTo(?array $to): void
    {
        $this->to = $to;
    }

    /**
     * Returns From.
     *
     * @return string[]|null
     */
    public function getFrom(): ?array
    {
        return $this->from;
    }

    /**
     * Sets From.
     *
     * @maps from
     *
     * @param string[]|null $from
     */
    public function setFrom(?array $from): void
    {
        $this->from = $from;
    }

    /**
     * Returns Currency.
     *
     * @return string[]|null
     */
    public function getCurrency(): ?array
    {
        return $this->currency;
    }

    /**
     * Sets Currency.
     *
     * @maps currency
     *
     * @param string[]|null $currency
     */
    public function setCurrency(?array $currency): void
    {
        $this->currency = $currency;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->to)) {
            $json['to']       = $this->to;
        }
        if (isset($this->from)) {
            $json['from']     = $this->from;
        }
        if (isset($this->currency)) {
            $json['currency'] = $this->currency;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
