<?php

declare(strict_types=1);

/*
 * VONQHiringAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VONQHiringAPILib\Models;

use stdClass;

class TargetGroupElement implements \JsonSerializable
{
    /**
     * @var string
     */
    private $description;

    /**
     * @var string
     */
    private $vonqId;

    /**
     * @param string $description
     * @param string $vonqId
     */
    public function __construct(string $description, string $vonqId)
    {
        $this->description = $description;
        $this->vonqId = $vonqId;
    }

    /**
     * Returns Description.
     * The vonq name for this target group element
     */
    public function getDescription(): string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     * The vonq name for this target group element
     *
     * @required
     * @maps description
     */
    public function setDescription(string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Vonq Id.
     * The Vonq ID representing this concept, as indicated in the [**`Taxonomy
     * Endpoints`**](#reference/experimental-products-search)
     */
    public function getVonqId(): string
    {
        return $this->vonqId;
    }

    /**
     * Sets Vonq Id.
     * The Vonq ID representing this concept, as indicated in the [**`Taxonomy
     * Endpoints`**](#reference/experimental-products-search)
     *
     * @required
     * @maps vonqId
     */
    public function setVonqId(string $vonqId): void
    {
        $this->vonqId = $vonqId;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['description'] = $this->description;
        $json['vonqId']      = $this->vonqId;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
