<?php

declare(strict_types=1);

/*
 * VONQHiringAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VONQHiringAPILib\Models;

use stdClass;

class TargetGroupPropertyValidationError implements \JsonSerializable
{
    /**
     * @var string[]|null
     */
    private $vonqId;

    /**
     * @var string[]|null
     */
    private $description;

    /**
     * Returns Vonq Id.
     *
     * @return string[]|null
     */
    public function getVonqId(): ?array
    {
        return $this->vonqId;
    }

    /**
     * Sets Vonq Id.
     *
     * @maps vonqId
     *
     * @param string[]|null $vonqId
     */
    public function setVonqId(?array $vonqId): void
    {
        $this->vonqId = $vonqId;
    }

    /**
     * Returns Description.
     *
     * @return string[]|null
     */
    public function getDescription(): ?array
    {
        return $this->description;
    }

    /**
     * Sets Description.
     *
     * @maps description
     *
     * @param string[]|null $description
     */
    public function setDescription(?array $description): void
    {
        $this->description = $description;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->vonqId)) {
            $json['vonqId']      = $this->vonqId;
        }
        if (isset($this->description)) {
            $json['description'] = $this->description;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
