<?php

declare(strict_types=1);

/*
 * VONQHiringAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VONQHiringAPILib\Models;

use stdClass;

class TargetGroup implements \JsonSerializable
{
    /**
     * @var TargetGroupElement[]
     */
    private $educationLevel;

    /**
     * @var TargetGroupElement[]
     */
    private $seniority;

    /**
     * @var TargetGroupElement[]
     */
    private $industry;

    /**
     * @var TargetGroupElement[]
     */
    private $jobCategory;

    /**
     * @param TargetGroupElement[] $educationLevel
     * @param TargetGroupElement[] $seniority
     * @param TargetGroupElement[] $industry
     * @param TargetGroupElement[] $jobCategory
     */
    public function __construct(array $educationLevel, array $seniority, array $industry, array $jobCategory)
    {
        $this->educationLevel = $educationLevel;
        $this->seniority = $seniority;
        $this->industry = $industry;
        $this->jobCategory = $jobCategory;
    }

    /**
     * Returns Education Level.
     * Education Level required by the Candidate. You can specify only one value.
     *
     * @return TargetGroupElement[]
     */
    public function getEducationLevel(): array
    {
        return $this->educationLevel;
    }

    /**
     * Sets Education Level.
     * Education Level required by the Candidate. You can specify only one value.
     *
     * @required
     * @maps educationLevel
     *
     * @param TargetGroupElement[] $educationLevel
     */
    public function setEducationLevel(array $educationLevel): void
    {
        $this->educationLevel = $educationLevel;
    }

    /**
     * Returns Seniority.
     * Seniority Level expected by the Candidate. You can specify only one value.
     *
     * @return TargetGroupElement[]
     */
    public function getSeniority(): array
    {
        return $this->seniority;
    }

    /**
     * Sets Seniority.
     * Seniority Level expected by the Candidate. You can specify only one value.
     *
     * @required
     * @maps seniority
     *
     * @param TargetGroupElement[] $seniority
     */
    public function setSeniority(array $seniority): void
    {
        $this->seniority = $seniority;
    }

    /**
     * Returns Industry.
     * The Industry related to the Position open. You can specify only one value.
     *
     * @return TargetGroupElement[]
     */
    public function getIndustry(): array
    {
        return $this->industry;
    }

    /**
     * Sets Industry.
     * The Industry related to the Position open. You can specify only one value.
     *
     * @required
     * @maps industry
     *
     * @param TargetGroupElement[] $industry
     */
    public function setIndustry(array $industry): void
    {
        $this->industry = $industry;
    }

    /**
     * Returns Job Category.
     * Job Category indicates the type of Position that's open. You can specify only one value.
     *
     * @return TargetGroupElement[]
     */
    public function getJobCategory(): array
    {
        return $this->jobCategory;
    }

    /**
     * Sets Job Category.
     * Job Category indicates the type of Position that's open. You can specify only one value.
     *
     * @required
     * @maps jobCategory
     *
     * @param TargetGroupElement[] $jobCategory
     */
    public function setJobCategory(array $jobCategory): void
    {
        $this->jobCategory = $jobCategory;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['educationLevel'] = $this->educationLevel;
        $json['seniority']      = $this->seniority;
        $json['industry']       = $this->industry;
        $json['jobCategory']    = $this->jobCategory;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
