<?php

declare(strict_types=1);

/*
 * VONQHiringAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VONQHiringAPILib\Models;

use stdClass;

class TaxonomyName implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $languageCode;

    /**
     * @var string|null
     */
    private $value;

    /**
     * Returns Language Code.
     * ICU Locale code for the Language of the taxonomy item
     */
    public function getLanguageCode(): ?string
    {
        return $this->languageCode;
    }

    /**
     * Sets Language Code.
     * ICU Locale code for the Language of the taxonomy item
     *
     * @maps languageCode
     * @factory \VONQHiringAPILib\Models\LanguageCodeEnum::checkValue
     */
    public function setLanguageCode(?string $languageCode): void
    {
        $this->languageCode = $languageCode;
    }

    /**
     * Returns Value.
     * The name of the taxonomy item in one defined Language
     */
    public function getValue(): ?string
    {
        return $this->value;
    }

    /**
     * Sets Value.
     * The name of the taxonomy item in one defined Language
     *
     * @maps value
     */
    public function setValue(?string $value): void
    {
        $this->value = $value;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->languageCode)) {
            $json['languageCode'] = LanguageCodeEnum::checkValue($this->languageCode);
        }
        if (isset($this->value)) {
            $json['value']        = $this->value;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
