<?php

declare(strict_types=1);

/*
 * VONQHiringAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VONQHiringAPILib;

/**
 * Environments available for API
 */
class Environment
{
    /**
     * Production
     */
    public const PRODUCTION = 'production';

    /**
     * Sandbox
     */
    public const SANDBOX = 'sandbox';
}
